### ISSUE TITLE
    DockerComposeError: Docker Compose error: No such service: drive_tenderdash

### ISSUE THREAD

**Issue by dashameter** [dashevo/dashmate#372]
```
dashmate group:status
Node local_1
╔═══════════════════╤══════════╗
║ Network           │ regtest  ║
║ Core Version      │ 0.17.0.0 ║
║ Core Status       │ running  ║
║ Masternode Status │ Ready    ║
║ Platform Version  │          ║
║ Platform Status   │ running  ║
╚═══════════════════╧══════════╝

Node local_2
╔═══════════════════╤══════════╗
║ Network           │ regtest  ║
║ Core Version      │ 0.17.0.0 ║
║ Core Status       │ running  ║
║ Masternode Status │ Ready    ║
║ Platform Version  │          ║
║ Platform Status   │ running  ║
╚═══════════════════╧══════════╝

Node local_3
╔═══════════════════╤══════════╗
║ Network           │ regtest  ║
║ Core Version      │ 0.17.0.0 ║
║ Core Status       │ running  ║
║ Masternode Status │ Ready    ║
║ Platform Version  │          ║
║ Platform Status   │ running  ║
╚═══════════════════╧══════════╝

Node local_seed
    DockerComposeError: Docker Compose error: No such service: drive_tenderdash


is this an issue ?

Node local_seed
    DockerComposeError: Docker Compose error: No such service: drive_tenderdash
```

trying to connect to dashmate throws

```
{
  dapiAddresses: [ '127.0.0.1:3000' ],
  wallet: {
    mnemonic: 'proud group frequent erase retire approve produce race wealth picnic alert pear'
  },
  apps: {
    dpns: { contractId: 'GbXk32LPBGa9RCWedT5JmRawYZy9ct2tjyiv881nfJWU' },
    primitives: { contractId: '42P3Ea9kj3TrAidcXw5q9BELtefr6kybSFaYDxA1QYw6' },
    jembe: { contractId: '5gKsEj1CetWCaGkzX6adV82asgG7eyE2QbjxusuKEiLN' }
  }
}
warn: Running on a NodeJS env without any specified adapter. Data will not persist.
Something went wrong:
 MaxRetriesReachedError: Max retries reached: 14 UNAVAILABLE: unavailable
    at GrpcTransport.request (jembe/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport.js:88:15) {
  error: Error: 14 UNAVAILABLE: unavailable
      at Object.exports.createStatusError (jembe/node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (jembe/node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener._callNext (jembe/node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (jembe/node_modules/grpc/src/client_interceptors.js:618:8)
      at InterceptingListener._callNext (jembe/node_modules/grpc/src/client_interceptors.js:574:12)
      at InterceptingListener.onReceiveStatus (jembe/node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (jembe/node_modules/grpc/src/client_interceptors.js:847:24) {
    code: 14,
    metadata: Metadata { _internal_repr: [Object], flags: 0 },
    details: 'unavailable'
  }
}
undefined
```

**Comment by dashameter** [comment]
appears fixed on v.20 master, closing for now
